<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.47">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>filter()</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="02-Filter_files/libs/clipboard/clipboard.min.js"></script>
<script src="02-Filter_files/libs/quarto-html/quarto.js"></script>
<script src="02-Filter_files/libs/quarto-html/popper.min.js"></script>
<script src="02-Filter_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="02-Filter_files/libs/quarto-html/anchor.min.js"></script>
<link href="02-Filter_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="02-Filter_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="02-Filter_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="02-Filter_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="02-Filter_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">filter()</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="choosing-rows" class="level1">
<h1>Choosing Rows</h1>
<p>Good scientists <strong>NEVER</strong> delete data from original records. The tidyverse allows us to create a new, clean dataset with a transparent set of steps from which we can create graphs, visualizations and analyses without losing any of the original data.</p>
<p>We here demonstrate how to define criteria for choosing which rows to include from the data. Consider the High School survey data which consists of responses to 60 questions from 312 high school students.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries and data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>survey <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">'https://github.com/byuistats/Math221D_Cannon/raw/master/Data/HighSchoolSeniors_subset.csv'</span>) <span class="sc">%&gt;%</span> <span class="fu">tibble</span>()</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 60
  Country Region DataYear ClassGrade Gender Ageyears Handed       Height_cm
  &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt;      &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
1 USA     FL         2022         12 Male         18 Left-Handed        182
2 USA     IN         2022         12 Male         17 Right-Handed       190
3 USA     GA         2022         12 Female       17 Right-Handed       172
4 USA     NC         2022         11 Female       15 Right-Handed       163
5 USA     CO         2022         12 Female       17 Left-Handed         51
6 USA     MO         2022         11 Male         17 Right-Handed       181
# ℹ 52 more variables: Footlength_cm &lt;dbl&gt;, Armspan_cm &lt;dbl&gt;,
#   Languages_spoken &lt;dbl&gt;, Travel_to_School &lt;chr&gt;,
#   Travel_time_to_School &lt;int&gt;, Reaction_time &lt;dbl&gt;,
#   Score_in_memory_game &lt;dbl&gt;, Favourite_physical_activity &lt;chr&gt;,
#   Imprtance_reducing_pllutin &lt;int&gt;, Imprtance_recycling_rubbish &lt;int&gt;,
#   Imprtance_cnserving_water &lt;int&gt;, Imprtance_saving_energy &lt;int&gt;,
#   Imprtance_wning_cmputer &lt;int&gt;, Imprtance_Internet_access &lt;int&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 312
Columns: 60
$ Country                          &lt;chr&gt; "USA", "USA", "USA", "USA", "USA", "U…
$ Region                           &lt;chr&gt; "FL", "IN", "GA", "NC", "CO", "MO", "…
$ DataYear                         &lt;int&gt; 2022, 2022, 2022, 2022, 2022, 2022, 2…
$ ClassGrade                       &lt;int&gt; 12, 12, 12, 11, 12, 11, 11, 11, 11, 1…
$ Gender                           &lt;chr&gt; "Male", "Male", "Female", "Female", "…
$ Ageyears                         &lt;dbl&gt; 18, 17, 17, 15, 17, 17, 17, 18, 16, 1…
$ Handed                           &lt;chr&gt; "Left-Handed", "Right-Handed", "Right…
$ Height_cm                        &lt;dbl&gt; 182.00, 190.00, 172.00, 163.00, 51.00…
$ Footlength_cm                    &lt;dbl&gt; 20.0, 28.0, 26.0, 23.0, 31.0, 28.0, 2…
$ Armspan_cm                       &lt;dbl&gt; 142.00, 192.00, 167.00, 160.00, 52.00…
$ Languages_spoken                 &lt;dbl&gt; 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1…
$ Travel_to_School                 &lt;chr&gt; "Car", "Car", "Car", "Car", "Car", "C…
$ Travel_time_to_School            &lt;int&gt; 25, 20, 5, 6, 15, 17, 15, 40, 20, 3, …
$ Reaction_time                    &lt;dbl&gt; 0.349, 0.358, 0.447, 0.438, 0.542, 0.…
$ Score_in_memory_game             &lt;dbl&gt; 34, 49, 46, 43, 61, 49, 40, 49, 44, 4…
$ Favourite_physical_activity      &lt;chr&gt; "Baseball/Softball", "Swimming", "Lac…
$ Imprtance_reducing_pllutin       &lt;int&gt; 650, 100, 610, 668, 1000, 199, 80, 70…
$ Imprtance_recycling_rubbish      &lt;int&gt; 400, 100, 519, 775, 1000, 133, 80, 50…
$ Imprtance_cnserving_water        &lt;int&gt; 550, 100, 422, 749, 1000, 179, 80, 10…
$ Imprtance_saving_energy          &lt;int&gt; 400, 100, 599, 797, 1000, 273, 90, 50…
$ Imprtance_wning_cmputer          &lt;int&gt; 500, 500, 797, 706, 20, 827, 90, 400,…
$ Imprtance_Internet_access        &lt;int&gt; 850, 500, 1000, 749, 123, 951, 100, 1…
$ Left_Footlength_cm               &lt;int&gt; 20, 28, 28, 23, 31, 27, 23, 21, 27, 2…
$ Longer_foot                      &lt;chr&gt; "Same length", "Same length", "Left f…
$ Index_Fingerlength_mm            &lt;int&gt; 64, 90, 70, 69, 103, 106, 69, 70, 10,…
$ Ring_Fingerlength_mm             &lt;int&gt; 76, 85, 75, 77, 100, 111, 75, 74, 9, …
$ Longer_Finger_Lefthand           &lt;chr&gt; "Ring finger", "Index finger", "Ring …
$ Birth_month                      &lt;chr&gt; "June", "January", "April", "May", "J…
$ Favorite_Season                  &lt;chr&gt; "Summer", "Winter", "Summer", "Spring…
$ Allergies                        &lt;chr&gt; "No", "No", "No", "No", "Yes", "No", …
$ Vegetarian                       &lt;chr&gt; "No", "No", "No", "No", "No", "No", "…
$ Favorite_Food                    &lt;chr&gt; "Meat", "Pizza/Pasta", "Breads/Sandwi…
$ Beverage                         &lt;chr&gt; "Water", "Soft drink (caffeinated)", …
$ Favorite_School_Subject          &lt;chr&gt; "History", "Mathematics and statistic…
$ Sleep_Hours_Schoolnight          &lt;dbl&gt; 6.5, 6.0, 7.0, 6.0, 6.0, 7.0, 4.0, 7.…
$ Sleep_Hours_Non_Schoolnight      &lt;dbl&gt; 7, 8, 9, 7, 12, 9, 6, 9, 8, 9, 6, 11,…
$ Home_Occupants                   &lt;dbl&gt; 6, 5, 2, 5, 3, 6, 6, 7, 3, 4, 6, 3, 5…
$ Home_Internet_Access             &lt;chr&gt; "Yes - broadband connection", "Yes - …
$ Communication_With_Friends       &lt;chr&gt; "Text messaging", "Text messaging", "…
$ Text_Messages_Sent_Yesterday     &lt;int&gt; 30, 20, 10, 450, 50, 36, 500, 75, 100…
$ Text_Messages_Received_Yesterday &lt;int&gt; 30, 20, 18, 420, 60, 31, 1000, 75, 10…
$ Hanging_Out_With_Friends_Hours   &lt;dbl&gt; 10, 10, 72, 5, 24, 4, 2, 5, 10, 8, 5,…
$ Talking_On_Phone_Hours           &lt;dbl&gt; 2, 0, 1, 15, 34, 1, 3, 3, 10, 2, 0, 1…
$ Doing_Homework_Hours             &lt;dbl&gt; 12.0, 0.0, 0.0, 8.0, 30.0, 8.0, 10.0,…
$ Doing_Things_With_Family_Hours   &lt;int&gt; 8, 5, 0, 8, 15, 13, 5, 10, 10, 6, 4, …
$ Outdoor_Activities_Hours         &lt;dbl&gt; 8, 20, 10, 3, 15, 5, 5, 1, 2, 1, 1, 2…
$ Video_Games_Hours                &lt;dbl&gt; 4.0, 10.0, 0.0, 2.0, 34.0, 13.0, 6.0,…
$ Social_Websites_Hours            &lt;dbl&gt; 1, 3, 100, 10, 25, 30, 2, 8, 10, 30, …
$ Texting_Messaging_Hours          &lt;dbl&gt; 2, 1, 50, 5, 20, 7, 2, 3, 9, 1, 24, 1…
$ Computer_Use_Hours               &lt;dbl&gt; 3, 20, 5, 15, 40, 13, 2, 24, 9, 1, 24…
$ Watching_TV_Hours                &lt;dbl&gt; 1, 20, 5, 4, 5, 41, 2, 2, 20, 6, 0, 2…
$ Paid_Work_Hours                  &lt;dbl&gt; 1, 0, 12, 0, 40, 20, 12, 1, 35, 14, 0…
$ Work_At_Home_Hours               &lt;dbl&gt; 1, 1, 1, 5, 10, 7, 4, 0, 9, 0, 2, 0, …
$ Schoolwork_Pressure              &lt;chr&gt; "Very little", "Some", "Some", "Some"…
$ Planned_Education_Level          &lt;chr&gt; "Graduate degree", "Graduate degree",…
$ Favorite_Music                   &lt;chr&gt; "Pop", "Techno/Electronic", "Rap/Hip …
$ Superpower                       &lt;chr&gt; "Telepathy", "Invisibility", "Telepat…
$ Preferred_Status                 &lt;chr&gt; "Happy", "Rich", "Rich", "Healthy", "…
$ Role_Model_Type                  &lt;chr&gt; "Sports person", "Sports person", "Re…
$ Charity_Donation                 &lt;chr&gt; "Health", "Arts, culture, sports", "H…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(survey<span class="sc">$</span>Computer_Use_Hours <span class="sc">~</span> survey<span class="sc">$</span>Gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  survey$Gender min   Q1 median     Q3 max     mean       sd   n missing
1        Female   0 8.00     15 25.500 168 22.81579 26.15705 152       0
2          Male   0 6.75     20 38.875 168 27.24687 29.39008 160       0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(survey<span class="sc">$</span>Computer_Use_Hours <span class="sc">~</span> survey<span class="sc">$</span>Gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-Filter_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(survey<span class="sc">$</span>Computer_Use_Hours <span class="sc">~</span> survey<span class="sc">$</span>Gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)]: non-numeric argument to binary operator</code></pre>
</div>
</div>
<section id="logical-operators" class="level2">
<h2 class="anchored" data-anchor-id="logical-operators">Logical Operators</h2>
<p>Logical operators are used extensively in computer programming to evaluate if a specified condition is met. They return a “True” or a “False” but are often treated as 1’s and 0’s respectively.</p>
<p>The most common logical operators used to filter rows are:</p>
<ul>
<li><code>&lt;</code> and <code>&lt;=</code> means “less than” and “less than or equal to” respectively</li>
<li><code>&gt;</code> and <code>&gt;=</code> means “greater than” and “greater than or equal to” respectively</li>
<li><code>==</code> means “equal to” (NOTE: we use double equals because in most computer languages, a single <code>=</code> is an assignment operator. This avoids ambiguity)</li>
<li><code>!=</code> means “not equal to”; this one is useful if you want to eliminate one level of a variable</li>
<li><code>%in%</code> selects specified levels you want to include</li>
</ul>
</section>
</section>
<section id="removing-outliers" class="level1">
<h1>Removing Outliers</h1>
<p>One common use of<code>filter()</code> is to remove outliers. Favstats of Height_cm shows that the tallest person is 999 cm. This means there is at least one impossible value we may not want to include in a visualization or analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(survey<span class="sc">$</span>Height_cm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  min  Q1 median      Q3 max     mean       sd   n missing
 1.68 161    170 178.125 999 169.2412 53.54382 312       0</code></pre>
</div>
</div>
<p>We can create a new dataset, <code>clean</code>, that excludes responses of people who are taller than 250cm (about 8 feet):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the %&gt;% operator throw survey data in to filer function, it's called "pipe"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>clean <span class="ot">&lt;-</span> survey <span class="sc">%&gt;%</span>  </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Height_cm <span class="sc">&lt;</span> <span class="dv">250</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># the dim() function shows us how many rows and columns in a dataset</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 312  60</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 310  60</code></pre>
</div>
</div>
<p>The above code will return a new dataset without the outliers.</p>
<p><strong>How many rows does the original dataset have?</strong> A: 312 rows</p>
<p><strong>How many rows does the filtered dataset have?</strong> A: 310 rows (2 rows of outliers were removed)</p>
<section id="filtering-on-categorical-data" class="level2">
<h2 class="anchored" data-anchor-id="filtering-on-categorical-data">Filtering on Categorical Data</h2>
<p>Suppose for some reason, we only want to include right- or left-handed people (excluding ambidextrous). We can add multiple conditions in the <code>filter()</code> function separated by a comma:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># See what the distinct values are in the Handed column (Get the column names)</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(survey<span class="sc">$</span>Handed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Left-Handed"  "Right-Handed" "Ambidextrous"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The table function tell you how many data in each of the column</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(survey<span class="sc">$</span>Handed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Ambidextrous  Left-Handed Right-Handed 
           9           36          267 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This following line applies multiple restrictions to the data set</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>survey <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Height_cm <span class="sc">&lt;</span> <span class="dv">250</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>         Handed <span class="sc">!=</span> <span class="st">"Ambidextrous"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 302 × 60
   Country Region DataYear ClassGrade Gender Ageyears Handed       Height_cm
   &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt;      &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
 1 USA     FL         2022         12 Male         18 Left-Handed        182
 2 USA     IN         2022         12 Male         17 Right-Handed       190
 3 USA     GA         2022         12 Female       17 Right-Handed       172
 4 USA     NC         2022         11 Female       15 Right-Handed       163
 5 USA     CO         2022         12 Female       17 Left-Handed         51
 6 USA     MO         2022         11 Male         17 Right-Handed       181
 7 USA     SC         2022         11 Female       18 Right-Handed       160
 8 USA     WA         2022         11 Female       16 Right-Handed       156
 9 USA     WA         2022         12 Female       17 Right-Handed       169
10 USA     WA         2022         11 Male         18 Right-Handed       160
# ℹ 292 more rows
# ℹ 52 more variables: Footlength_cm &lt;dbl&gt;, Armspan_cm &lt;dbl&gt;,
#   Languages_spoken &lt;dbl&gt;, Travel_to_School &lt;chr&gt;,
#   Travel_time_to_School &lt;int&gt;, Reaction_time &lt;dbl&gt;,
#   Score_in_memory_game &lt;dbl&gt;, Favourite_physical_activity &lt;chr&gt;,
#   Imprtance_reducing_pllutin &lt;int&gt;, Imprtance_recycling_rubbish &lt;int&gt;,
#   Imprtance_cnserving_water &lt;int&gt;, Imprtance_saving_energy &lt;int&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can also use %in% c("column") to select the columns you want</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>survey <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Height_cm <span class="sc">&lt;</span> <span class="dv">250</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>         Handed <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Left-Handed"</span>, <span class="st">"Right-Handed"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 302 × 60
   Country Region DataYear ClassGrade Gender Ageyears Handed       Height_cm
   &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt;      &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
 1 USA     FL         2022         12 Male         18 Left-Handed        182
 2 USA     IN         2022         12 Male         17 Right-Handed       190
 3 USA     GA         2022         12 Female       17 Right-Handed       172
 4 USA     NC         2022         11 Female       15 Right-Handed       163
 5 USA     CO         2022         12 Female       17 Left-Handed         51
 6 USA     MO         2022         11 Male         17 Right-Handed       181
 7 USA     SC         2022         11 Female       18 Right-Handed       160
 8 USA     WA         2022         11 Female       16 Right-Handed       156
 9 USA     WA         2022         12 Female       17 Right-Handed       169
10 USA     WA         2022         11 Male         18 Right-Handed       160
# ℹ 292 more rows
# ℹ 52 more variables: Footlength_cm &lt;dbl&gt;, Armspan_cm &lt;dbl&gt;,
#   Languages_spoken &lt;dbl&gt;, Travel_to_School &lt;chr&gt;,
#   Travel_time_to_School &lt;int&gt;, Reaction_time &lt;dbl&gt;,
#   Score_in_memory_game &lt;dbl&gt;, Favourite_physical_activity &lt;chr&gt;,
#   Imprtance_reducing_pllutin &lt;int&gt;, Imprtance_recycling_rubbish &lt;int&gt;,
#   Imprtance_cnserving_water &lt;int&gt;, Imprtance_saving_energy &lt;int&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We could also try using %in% instead of  "!="</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>survey <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Height_cm <span class="sc">&lt;</span> <span class="dv">250</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>         Handed <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Left-Handed"</span>, <span class="st">"Right-Handed"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 302 × 60
   Country Region DataYear ClassGrade Gender Ageyears Handed       Height_cm
   &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt;      &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
 1 USA     FL         2022         12 Male         18 Left-Handed        182
 2 USA     IN         2022         12 Male         17 Right-Handed       190
 3 USA     GA         2022         12 Female       17 Right-Handed       172
 4 USA     NC         2022         11 Female       15 Right-Handed       163
 5 USA     CO         2022         12 Female       17 Left-Handed         51
 6 USA     MO         2022         11 Male         17 Right-Handed       181
 7 USA     SC         2022         11 Female       18 Right-Handed       160
 8 USA     WA         2022         11 Female       16 Right-Handed       156
 9 USA     WA         2022         12 Female       17 Right-Handed       169
10 USA     WA         2022         11 Male         18 Right-Handed       160
# ℹ 292 more rows
# ℹ 52 more variables: Footlength_cm &lt;dbl&gt;, Armspan_cm &lt;dbl&gt;,
#   Languages_spoken &lt;dbl&gt;, Travel_to_School &lt;chr&gt;,
#   Travel_time_to_School &lt;int&gt;, Reaction_time &lt;dbl&gt;,
#   Score_in_memory_game &lt;dbl&gt;, Favourite_physical_activity &lt;chr&gt;,
#   Imprtance_reducing_pllutin &lt;int&gt;, Imprtance_recycling_rubbish &lt;int&gt;,
#   Imprtance_cnserving_water &lt;int&gt;, Imprtance_saving_energy &lt;int&gt;, …</code></pre>
</div>
</div>
<p><strong>NOTE</strong>: The <code>%in%</code> and the <code>!=</code> will not always give you the same results. If there are misspellings or other options, using <code>%in%</code> will limit the data to only those with the exact spelling in the list provided. For example, someone responding “left handed” (all lower case), would not be included in the clean data. Misspellings would, however, be included if I use <code>!= "Ambitextrous"</code> because that only removes rows written exactly that way. Things like, <code>ambidextrious</code> or <code>RightHanded</code> would still be included.</p>
<p>I could further limit my data to students from Florida and Missouri:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> survey <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Height_cm <span class="sc">&lt;</span> <span class="dv">250</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>         Handed <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Left-Handed"</span>, <span class="st">"Right-Handed"</span>),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>         Region <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"MO"</span>, <span class="st">"FL"</span>)) <span class="co"># %&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># select(......) You can also pipe the data that you already piped!!</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(new_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27 60</code></pre>
</div>
</div>
<p><strong>How many rows does our latest dataset have?</strong> A: 27 rows</p>
</section>
</section>
<section id="your-turn" class="level1">
<h1>Your turn</h1>
<p>How many vegetarians in the survey say that meat is their favorite food? A: 1</p>
<p>The <code>Vegetarian</code> column has “Yes” and “No” as possible options.</p>
<p>The <code>Favorite_Food</code> column has “Meat”, “Pizza/Pasta”, “Breads/Sandwiches”, “Rice/Noodle dishes”, “Poultry”, “Seafood”, “Vegetables”, “Desserts”, “Fruit”, “Salads”, “No favorite”, “Other” and “Soups” as options.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>vegetarians <span class="ot">&lt;-</span> survey <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Vegetarian <span class="sc">==</span> <span class="st">"Yes"</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>          Favorite_Food <span class="sc">==</span> <span class="st">"Meat"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(vegetarians)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1 60</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(survey<span class="sc">$</span>Favorite_Food)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Meat"               "Pizza/Pasta"        "Breads/Sandwiches" 
 [4] "Rice/Noodle dishes" "Poultry"            "Seafood"           
 [7] "Vegetables"         "Desserts"           "Fruit"             
[10] "Salads"             "No favorite"        "Other"             
[13] "Soups"             </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(clean<span class="sc">$</span>Height_cm <span class="sc">~</span> clean<span class="sc">$</span>Favorite_Food)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-Filter_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>