<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.47">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Comparing Means</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="09-AA_Unit4_Review_files/libs/clipboard/clipboard.min.js"></script>
<script src="09-AA_Unit4_Review_files/libs/quarto-html/quarto.js"></script>
<script src="09-AA_Unit4_Review_files/libs/quarto-html/popper.min.js"></script>
<script src="09-AA_Unit4_Review_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="09-AA_Unit4_Review_files/libs/quarto-html/anchor.min.js"></script>
<link href="09-AA_Unit4_Review_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="09-AA_Unit4_Review_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="09-AA_Unit4_Review_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="09-AA_Unit4_Review_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="09-AA_Unit4_Review_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Comparing Means</h1>
<p class="subtitle lead">Unit 2 Review</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In this activity, you will use everything we’ve covered up to this point including:</p>
<ul>
<li>Data manipulation using tidyverse functions</li>
<li>Hypothesis tests
<ul>
<li>1-Sample t-test</li>
<li>2-sample dependent t-test</li>
<li>2-sample independent t-test</li>
<li>ANOVA</li>
</ul></li>
<li>Confidence Intervals where applicable</li>
</ul>
<p>We will be using data collected about students in 2 Portuguese schools including their final grade. The goal is to answer research questions using statistical methods to see what factors significantly impact final grades.</p>
<section id="getting-to-know-a-new-dataset" class="level2">
<h2 class="anchored" data-anchor-id="getting-to-know-a-new-dataset">Getting to know a new dataset</h2>
<p>In class, we have reinforced a process for approaching a new dataset. The following is a summary of activities that help us conduct good research:</p>
<ul>
<li><strong>Read in the data</strong><br>
</li>
<li><strong>Explore the dataset as a whole</strong>:
<ul>
<li>What are the column names? What do they mean? Where can I find information about them?</li>
<li>What is the response/dependent variable? Could there be more than one?</li>
<li>What are some factors that may impact the response variable? Which are likely the most important?</li>
</ul></li>
<li><strong>Explore specific columns</strong>
<ul>
<li>Start with the response variable. Are there any outliers? Obtain summary statistics (<code>favstats()</code>), visualize the data (<code>histogram()</code>, <code>boxplot()</code>).</li>
<li>Explore the explanatory variables you think are most impact to the response variable. What type of data are they (categorical, quantitative)? For categorical variables, what are all the levels (<code>unique()</code>)</li>
</ul></li>
<li><strong>Formalize statistical hypotheses</strong>. If your factors are categorical, how many groups will you be comparing? Is it a 1-sample t-test, 2-sample t-test, ANOVA?</li>
<li><strong>Prepare data for analysis</strong>. You may need to clean the data (eg. <code>data %&gt;% filter() %&gt;% select()</code>)</li>
<li><strong>Perform the appropriate analysis</strong> (<code>t.test()</code>, <code>aov()</code>)</li>
</ul>
<p>All these activities are important, but we may spend more or less time on any one of them depending on the state of the data.</p>
</section>
<section id="load-the-libraries-and-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-libraries-and-data">Load the Libraries and Data</h2>
</section>
</section>
<section id="review-the-data" class="level1">
<h1>Review the data</h1>
<p>Take some time to familiarize yourself with the data. Check the <a href="https://www.kaggle.com/datasets/whenamancodes/student-performance">website</a> to see what the columns are.</p>
<p>What is the response variable? A: The final grade, G3</p>
<p>Create a histogram of the response variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(student<span class="sc">$</span>G3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(student<span class="sc">$</span>G3 <span class="sc">~</span> student<span class="sc">$</span>Medu, <span class="at">main =</span> <span class="st">"Student Final Academic Grade with different Mother Education Level"</span>, <span class="at">xlab =</span> <span class="st">"Student Mother Education Level"</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What do you notice about the shape of the distribution?<br>
:It’s close to symmetric, but there’s a gap around x = 3.</p>
<p>What anomalies, if any, do you notice?<br>
:The density at x = 0 is way higher than its surrounding area.</p>
<p>Calculate summary statistics for the response variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(student<span class="sc">$</span>G3) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">10.41519</td>
<td style="text-align: right;">4.581443</td>
<td style="text-align: right;">395</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Question</strong>: What is the minimum?<br>
<strong>Answer</strong>: 0</p>
<p><strong>Question</strong>: What is the maximum?<br>
<strong>Answer</strong>: 20</p>
<p><strong>Question</strong>: How many students participated in the survey?<br>
<strong>Answer</strong>: 395</p>
<p><strong>Question</strong>: Rank order the top 5 explanatory variables you think most influence the response and identify each as a categorical or quantitative variable:</p>
<ol type="1">
<li>Fedu (Father’s education. Categorical)</li>
<li>Medu (Mother’s education. Categorical)</li>
<li>studytime (weekly study time, Categorical)</li>
<li>reason (reason to choose this school, Categorical)</li>
<li>failures (number of past class failures, Categorical)</li>
</ol>
<p><strong>NOTE</strong>: Some of the above variables may be quantitative, which is great! Next unit will cover how to analyze those relationships. This assignment, however, focuses on comparing differences between groups and only considers categorical explanatory variables variables.</p>
</section>
<section id="preparing-data-for-analysis" class="level1">
<h1>Preparing data for analysis</h1>
<section id="categories-labeled-as-numbers" class="level2">
<h2 class="anchored" data-anchor-id="categories-labeled-as-numbers">Categories Labeled as Numbers</h2>
<p>Sometimes even correct data can have issues that must be addressed. For example, categories are often labeled as numbers. Software can’t guess when numbers are supposed to be categories, so we have to tell R when a number should be treated as a category.</p>
<p>To force a variable to be a category, we use the <code>factor()</code> function in R. We can change the variable type in the data itself or change it in the analysis. We demonstrate both methods below.</p>
<section id="changing-a-column-type-in-a-dataset" class="level3">
<h3 class="anchored" data-anchor-id="changing-a-column-type-in-a-dataset">Changing a Column Type in a dataset</h3>
<p>Father’s education, <code>Fedu</code>, shows up as a number in R. The website suggests that the numbers represent categories (0 = none, 1 = primary education (4th grade), 2 = 5th to 9th grade, 3 = secondary education or 4 = higher education).</p>
<p>To change the data type in the data itself, we can use a ‘mutate’ statement in the following manner:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new dataset called fedu_data that begins with the clean data and adds a column that we called Fedu_factor, which is the factorized column, Fedu:</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># mutate: create new column</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> student <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Fedu_factor =</span> <span class="fu">factor</span>(Fedu))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the column names of the new dataset.  Notice the new column</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># names('dataset') shows all of the column names</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(new_data)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># glimpse() shows us data types.  Notice after Fedu_factor, the &lt;fct&gt;, which shows us that this is in fact, a factor variable type.  &lt;dbl&gt; stands for "double" and is a numeric variable type</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(new_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="changing-the-variable-type-on-the-fly" class="level3">
<h3 class="anchored" data-anchor-id="changing-the-variable-type-on-the-fly">Changing the Variable Type “on the fly”</h3>
<p>You may not want to bother changing all the variable types for each potential analysis. Fortunately, you can create a factor “on the fly” within the analysis function itself.</p>
<p>Because there are more than 2 levels of Father’s Education, I will demonstrate how this is done in an ANOVA:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Force Fedu to be treated like a category in ANOVA:</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>fedu_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(student<span class="sc">$</span>G3 <span class="sc">~</span> <span class="fu">factor</span>(student<span class="sc">$</span>Fedu)) <span class="co">#method 1: using factor() to convert the original column</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fedu_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Df Sum Sq Mean Sq F value Pr(&gt;F)  
factor(student$Fedu)   4    238   59.53   2.891 0.0222 *
Residuals            390   8032   20.59                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fedu_anova2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(new_data<span class="sc">$</span>G3 <span class="sc">~</span> new_data<span class="sc">$</span>Fedu_factor) <span class="co">#method 2: using the new data set and the new factor column</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(predvars, data, env): object 'new_data' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fedu_anova2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in h(simpleError(msg, call)): error in evaluating the argument 'object' in selecting a method for function 'summary': object 'fedu_anova2' not found</code></pre>
</div>
</div>
<p>This works with most analysis functions including <code>t.test()</code> and <code>aov()</code>.</p>
<p><strong>NOTE</strong>: You only have to do this for variables in a dataset that are ‘categories labeled as numbers.’ If the categories are text, <code>t.test()</code> and <code>aov()</code> automatically recognizes the variable as categorical. However, it does no harm to put a column with text into a <code>factor()</code> statement.</p>
</section>
</section>
<section id="cleaning-the-data" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-the-data">Cleaning the Data</h2>
<p>While exploring the data, you may have noticed a few students ended up with a final grade of zero. While it may be interesting to explore what factors lead to an incomplete grade, we want to make conclusions about students who completed the course.</p>
<p>Create a clean dataset called, <code>clean</code>, that excludes zeros for G3. This will be used for the following analyses.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>clean <span class="ot">&lt;-</span> student <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(student<span class="sc">$</span>G3 <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(clean<span class="sc">$</span>G3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "school"     "sex"        "age"        "address"    "famsize"   
 [6] "Pstatus"    "Medu"       "Fedu"       "Mjob"       "Fjob"      
[11] "reason"     "guardian"   "traveltime" "studytime"  "failures"  
[16] "schoolsup"  "famsup"     "paid"       "activities" "nursery"   
[21] "higher"     "internet"   "romantic"   "famrel"     "freetime"  
[26] "goout"      "Dalc"       "Walc"       "health"     "absences"  
[31] "G1"         "G2"         "G3"        </code></pre>
</div>
</div>
</section>
</section>
<section id="perform-the-appropriate-analysis" class="level1">
<h1>Perform the Appropriate Analysis</h1>
<section id="comparing-schools" class="level2">
<h2 class="anchored" data-anchor-id="comparing-schools">Comparing Schools</h2>
<p>Suppose the Gabriel Pereira school (GP) has more stringent admissions requirements. We suspect this would lead to higher grades, on average.</p>
<p>Create a side-by-side boxplot of the final grades for each school. Change the y-axis label to read “Final Grade out of 20”, the x-axis label to read “School”, and add a title.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(clean<span class="sc">$</span>G3 <span class="sc">~</span> clean<span class="sc">$</span>school, <span class="at">xlab =</span> <span class="st">"School"</span>, <span class="at">ylab=</span><span class="st">"Final Grade out of 20"</span>, <span class="at">main =</span> <span class="st">"Student Final Grades from Different School"</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Question</strong>: What do you notice?<br>
<strong>Answer</strong>: GP, Gabriel Pereira school, has the higher student final grades than MS, Mousinho da Silveira school.</p>
<p>Create a table of summary statistics of final grade for each school:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(clean<span class="sc">$</span>G3 <span class="sc">~</span> clean<span class="sc">$</span>school) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">clean$school</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GP</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">11.62222</td>
<td style="text-align: right;">3.241866</td>
<td style="text-align: right;">315</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">MS</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">10.78571</td>
<td style="text-align: right;">3.056666</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="hypothesis-test" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-test">Hypothesis Test</h3>
<p>Create a qqPlot to look at the normality of both groups:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(clean<span class="sc">$</span>G3 <span class="sc">~</span> clean<span class="sc">$</span>school)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Question</strong>: Do the grades look normally distributed for both groups? If not, should we be concerned?<br>
<strong>Answer</strong>: Yes, they look normally distributed. Even if they are not, since the amount of data are both bigger than 30, which are normal distributed as well(according to CLT).</p>
<p><strong>Question</strong>: Can we trust the P-value?<br>
<strong>Answer</strong>: Yes since both groups are normally distributed.</p>
<p>State your null and alternative hypotheses and significance level.</p>
<p><strong>NOTE</strong>: Recall that R uses alphabetical order to determine which group is the reference group. It is useful to put this group on the left side of the null hypothesis and set your alternative hypothesis accordingly.</p>
<p><span class="math display">\[H_o: u_{GP} = u_{MS}\]</span></p>
<p><span class="math display">\[H_a: u_{GP} &gt; u_{MS}\]</span></p>
<p><span class="math display">\[\alpha = 0.05\]</span><br>
Perform the appropriate statistical test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(clean<span class="sc">$</span>G3 <span class="sc">~</span> clean<span class="sc">$</span>school, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  clean$G3 by clean$school
t = 1.6539, df = 54.062, p-value = 0.05197
alternative hypothesis: true difference in means between group GP and group MS is greater than 0
95 percent confidence interval:
 -0.009944032          Inf
sample estimates:
mean in group GP mean in group MS 
        11.62222         10.78571 </code></pre>
</div>
</div>
<p><strong>Question</strong>: What is the P-value?<br>
<strong>Answer</strong>: p-value = 0.05197</p>
<p><strong>Question</strong>: What is your conclusion in context of the research question?<br>
<strong>Answer</strong>: I have sufficient evidence to suggest Gabriel Pereira School has the same average student final grade with Mousinho da Silveira School.</p>
</section>
<section id="confidence-interval" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval">Confidence Interval</h3>
<p>Create a <span class="math inline">\((1-\alpha)\)</span>% confidence interval and explain it in context of the research question.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(clean<span class="sc">$</span>G3 <span class="sc">~</span> clean<span class="sc">$</span>school, <span class="at">conf.level =</span> <span class="dv">1</span><span class="fl">-0.05</span>)<span class="sc">$</span>conf.int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1775092  1.8505250
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
</div>
<p><strong>Explanation</strong>: I’m 95% confident that the difference student final grade between Gabriel Pereira School and Mousinho da Silveira School, on average, is located between -0.1775092 and 1.8505250.</p>
</section>
</section>
<section id="comparing-second-period-grade-with-final-grade" class="level2">
<h2 class="anchored" data-anchor-id="comparing-second-period-grade-with-final-grade">Comparing Second Period Grade with Final Grade</h2>
<p>We suspect there is a difference between the second period and the final grade, though we do not know if they go up or down. Carry out a hypothesis test to evaluate this suspicion.</p>
<section id="hypothesis-test-1" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-test-1">Hypothesis Test</h3>
<p>Choose how you will define the difference between final grade and second period grade, and create a new object called <code>diff</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>diff <span class="ot">&lt;-</span> clean<span class="sc">$</span>G3 <span class="sc">-</span> clean<span class="sc">$</span>G2 <span class="co"># If diff &gt; 0, it means G3 &gt; G2, the grade goes up. Vice Versa</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Question</strong>: What does a negative number mean?<br>
<strong>Answer</strong>: G3 &lt; G2, the grade goes down.</p>
<p>Create a <code>qqPlot()</code> of <code>diff</code> and check for normality:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(diff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44 62</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(diff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> min Q1 median Q3 max      mean        sd   n missing
  -2  0      0  1   3 0.1652661 0.8400931 357       0</code></pre>
</div>
</div>
<p><strong>Question</strong>: Do the grade differences look normally distributed? If not, should we be concerned?<br>
<strong>Answer</strong>: No, it looks skewed. However, since the amount of data is bigger than 30 (357 &gt; 30), we don’t need to be concerned about it.</p>
<p><strong>Question</strong>: Can we trust the P-value?<br>
<strong>Answer</strong>: Yes you can, since the amount of data &gt; 30, it’s normally distributed.</p>
<p>State your null and alternative hypothesis and choose a significance level:</p>
<p><span class="math display">\[H_o: u_{diff} = 0\]</span></p>
<p><span class="math display">\[Ha: u_{diff} &gt; 0\]</span></p>
<p><span class="math display">\[\alpha = 0.05\]</span></p>
<p>Perform the appropriate analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(diff, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  diff
t = 3.717, df = 356, p-value = 0.000117
alternative hypothesis: true mean is greater than 0
95 percent confidence interval:
 0.09194109        Inf
sample estimates:
mean of x 
0.1652661 </code></pre>
</div>
</div>
<p><strong>Question</strong>: What is the P-value?<br>
<strong>Answer</strong>: p-value = 0.000117</p>
<p><strong>Question</strong>: What conclusion do you make in context of this research question?<br>
<strong>Answer</strong>: I have sufficient evidence to suggest that the average final grade is higher than the second period grade.</p>
</section>
<section id="confidence-interval-1" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-1">Confidence Interval</h3>
<p>Create a <span class="math inline">\((1-\alpha)\)</span>% confidence interval for the differences and explain it in context of the research question.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(diff, <span class="at">conf.level =</span> <span class="dv">1</span><span class="fl">-0.05</span>)<span class="sc">$</span>conf.int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07782404 0.25270817
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
</div>
<p><strong>Explanation</strong>: I’m 95% confident that the difference between student final grade and second period grade, on average, is located between 0.07782404 and 0.25270817.</p>
</section>
</section>
<section id="absenteeism-in-portugal" class="level2">
<h2 class="anchored" data-anchor-id="absenteeism-in-portugal">Absenteeism in Portugal</h2>
<p>In 2021, Portugal <a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Secondary_education_statistics#Out-of-school_rates">reported</a> having 0% absenteeism for 15-year-olds. We suspect that the actual absenteeism is higher than the reported value (zero).</p>
<section id="hypothesis-test-2" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-test-2">Hypothesis Test</h3>
<p>Create a <code>qqPlot()</code> for absences.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>fifteen_absences <span class="ot">&lt;-</span> clean <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(clean<span class="sc">$</span>age <span class="sc">==</span> <span class="dv">15</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(fifteen_absences<span class="sc">$</span>absences)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 55 39</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(fifteen_absences<span class="sc">$</span>absences)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> min Q1 median Q3 max     mean       sd  n missing
   0  0      2  6  26 3.605263 4.118508 76       0</code></pre>
</div>
</div>
<p><strong>Question</strong>: Do absences look normally distributed? If not, should we be concerned?<br>
<strong>Answer</strong>: It looks alright, just with some skewed dots in the bottom part. Since the amount of data is big enough (357 &gt; 30), we know it’s normally distributed.</p>
<p><strong>Question</strong>: Can we trust the P-value?<br>
<strong>Answer</strong>: Yes since the data is normally distributed.</p>
<p>State your null and alternative hypotheses and choose a significance level:</p>
<p><span class="math display">\[H_o: u_a = 0\]</span></p>
<p><span class="math display">\[H_a: u_a &gt; 0\]</span></p>
<p><span class="math display">\[\alpha = 0.05\]</span></p>
<p>Perform the appropriate analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(fifteen_absences<span class="sc">$</span>absences, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  fifteen_absences$absences
t = 7.6314, df = 75, p-value = 2.991e-11
alternative hypothesis: true mean is greater than 0
95 percent confidence interval:
 2.818474      Inf
sample estimates:
mean of x 
 3.605263 </code></pre>
</div>
</div>
<p><strong>Question</strong>: What is the P-value?<br>
<strong>Answer</strong>: p-value = 2.991e-11</p>
<p><strong>Question</strong>: What conclusion do you make in context of this research question?<br>
<strong>Answer</strong>: I have sufficient evidence to suggest that the 15 year-old school absence times, on average, is bigger than 0.</p>
</section>
<section id="confidence-interval-2" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-2">Confidence Interval</h3>
<p>Create a <span class="math inline">\((1-\alpha)\)</span>% confidence interval for average absences and interpret it in context of the problem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(fifteen_absences<span class="sc">$</span>absences, <span class="at">conf.level =</span> <span class="dv">1</span><span class="fl">-0.05</span>)<span class="sc">$</span>conf.int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.664144 4.546382
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
</div>
<p><strong>Explanation</strong>: I’m 95% confident that the average number of school absence of 15 year-old students is located between 2.664144 and 4.546382.</p>
</section>
</section>
<section id="the-impact-of-mothers-education-level" class="level2">
<h2 class="anchored" data-anchor-id="the-impact-of-mothers-education-level">The Impact of Mother’s Education Level</h2>
<p>The level of education of the mother in the home is thought to have a significant impact on student success.</p>
<p>Create a side-by-side boxplot of final grades for each level of mother’s education.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(student<span class="sc">$</span>G3 <span class="sc">~</span> student<span class="sc">$</span>Medu, <span class="at">main =</span> <span class="st">"Student Final Academic Grade with different Mother Education Levels"</span>, <span class="at">xlab =</span> <span class="st">"Student Mother Education Levels"</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Create a table of summary statistics of final grades for each level of mother’s education.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(student<span class="sc">$</span>G3 <span class="sc">~</span> student<span class="sc">$</span>Medu) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 5%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">student$Medu</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">13.000000</td>
<td style="text-align: right;">3.464102</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">8.677966</td>
<td style="text-align: right;">4.364594</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8.0</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">9.728155</td>
<td style="text-align: right;">4.636163</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8.0</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">10.303030</td>
<td style="text-align: right;">4.623486</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">11.763359</td>
<td style="text-align: right;">4.267646</td>
<td style="text-align: right;">131</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Question</strong>: How many respondents have a mother with no formal education (level 0)?<br>
<strong>Answer</strong>: 3</p>
<p>Create a new dataset, <code>clean_medu</code>, that does not include mother’s education level 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>clean_medu <span class="ot">&lt;-</span> clean <span class="sc">%&gt;%</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(clean<span class="sc">$</span>Medu <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(clean_medu<span class="sc">$</span>G3 <span class="sc">~</span> clean_medu<span class="sc">$</span>Medu)<span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 5%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">clean_medu$Medu</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">10.24000</td>
<td style="text-align: right;">2.495383</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13.00</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">11.25843</td>
<td style="text-align: right;">2.736654</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13.75</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">11.33333</td>
<td style="text-align: right;">3.424958</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">12.32800</td>
<td style="text-align: right;">3.475202</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Create another boxplot with the new dataset that excludes level 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(clean_medu<span class="sc">$</span>G3 <span class="sc">~</span> clean_medu<span class="sc">$</span>Medu, <span class="at">main =</span> <span class="st">"Student Final Academic Grade with different Mother Education Levels"</span>, <span class="at">xlab =</span> <span class="st">"Student Mother Education Levels"</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Create a summary table of final grades for each level of a mother’s education with the new dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(clean_medu<span class="sc">$</span>G3 <span class="sc">~</span> clean_medu<span class="sc">$</span>Medu) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 5%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">clean_medu$Medu</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">10.24000</td>
<td style="text-align: right;">2.495383</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13.00</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">11.25843</td>
<td style="text-align: right;">2.736654</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13.75</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">11.33333</td>
<td style="text-align: right;">3.424958</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">12.32800</td>
<td style="text-align: right;">3.475202</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>sds <span class="ot">=</span> <span class="fu">favstats</span>(clean_medu<span class="sc">$</span>G3 <span class="sc">~</span> clean_medu<span class="sc">$</span>Medu)<span class="sc">$</span>sd</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(sds)<span class="sc">/</span><span class="fu">min</span>(sds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.392653</code></pre>
</div>
</div>
<p><strong>Question</strong>: What is the maximum standard deviation?<br>
<strong>Answer</strong>: 3.475202</p>
<p><strong>Question</strong>: What is the minimum standard deviation?<br>
<strong>Answer</strong>: 2.495383</p>
<p><strong>Question</strong>: Verify that the maximum is less than twice as large as the minimum to check the “equality of standard deviations”.<br>
<strong>Answer</strong>: Yes, the ratio of maximum and minimum of standard deviations is 1.392653.</p>
<section id="hypothesis-test-3" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-test-3">Hypothesis Test</h3>
<p>State your null and alternative hypotheses and pick alpha:</p>
<p><span class="math display">\[H_o: u_1 = u_2 = u_3 = u_4\]</span></p>
<p><span class="math display">\[H_a: At\ least\ one\ of\ them\ not\ equals\ to\ one\ another.\]</span></p>
<p><span class="math display">\[\alpha = 0.05\]</span></p>
<p>Perform the appropriate statistical test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>aov_medu <span class="ot">&lt;-</span> <span class="fu">aov</span>(clean_medu<span class="sc">$</span>G3 <span class="sc">~</span> clean_medu<span class="sc">$</span>Medu)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov_medu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Df Sum Sq Mean Sq F value  Pr(&gt;F)    
clean_medu$Medu   1    157   157.5   15.74 8.8e-05 ***
Residuals       352   3521    10.0                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Question</strong>: What is the test statistic?<br>
<strong>Answer</strong>: F-value = 15.74</p>
<p><strong>Question</strong>: What is the P-value?<br>
<strong>Answer</strong>: P-value = 8.8e-05</p>
<p>Check the normality of the residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(aov_medu<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 198 260</code></pre>
</div>
</div>
<p><strong>Question</strong>: Do the residuals appear roughly normally distributed?<br>
<strong>Answer</strong>: Yes. It looks normally distributed according to qqPlot graph.</p>
<p><strong>Question</strong>: Can we trust the P-value.<br>
<strong>Answer</strong>: Yes since the data is normally distributed.</p>
<p>State your conclusion: I have sufficient evidence to suggest that the student final grades among different mother education levels, on average, are not equal to each other.</p>
</section>
</section>
<section id="choose-your-own-adventure" class="level2">
<h2 class="anchored" data-anchor-id="choose-your-own-adventure">Choose your own adventure</h2>
<p>Pick another variable that was not analyzed above: failures (number of past class failures, Categorical)</p>
<p>Create a side-by-side boxplot. Be sure to properly label the graph and add sufficient information so readers can know what they are looking at without having to search through the report or code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(clean<span class="sc">$</span>G3 <span class="sc">~</span> clean<span class="sc">$</span>failures)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  clean$failures min    Q1 median    Q3 max      mean       sd   n missing
1              0   5 10.00   11.5 14.00  20 11.942177 3.193432 294       0
2              1   5  8.00   10.0 12.00  18 10.150000 2.597336  40       0
3              2   4  7.75    9.0  9.25  15  8.833333 3.010084  12       0
4              3   5  7.00    8.0 10.00  10  8.272727 1.678744  11       0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(clean<span class="sc">$</span>G3 <span class="sc">~</span> clean<span class="sc">$</span>failures, <span class="at">xlab =</span> <span class="st">"Number of Past Class Failures (n if 1&lt;=n&lt;=3, else 4)"</span>, <span class="at">ylab =</span> <span class="st">"Final Grade out of 20"</span>, <span class="at">main =</span> <span class="st">"Student Final Grades with Number of Past Class Failures"</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Perform the appropriate analysis. Be sure to include a concise conclusion in the context of the research question, including a hypothesis test (and confidence interval if applicable.)</p>
<p>Hypothesis Statement: <span class="math display">\[H_o = u_0 = u_1 = u_2 = u_3 \]</span> <span class="math display">\[H_a = At\ least\ one\ of\ the\ mean\ not\ equals\ to\ one\ another.\]</span> <span class="math display">\[\alpha = 0.05\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>aov_failure <span class="ot">&lt;-</span> <span class="fu">aov</span>(clean<span class="sc">$</span>G3 <span class="sc">~</span> clean<span class="sc">$</span>failures)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov_failure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df Sum Sq Mean Sq F value   Pr(&gt;F)    
clean$failures   1    320   320.2   33.55 1.53e-08 ***
Residuals      355   3389     9.5                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Question</strong>: What is the test statistic?<br>
<strong>Answer</strong>: F-value = 33.55</p>
<p><strong>Question</strong>: What is the P-value?<br>
<strong>Answer</strong>: P-value = 1.53e-08</p>
<p>Check the normality of the residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>sds_failure <span class="ot">&lt;-</span> <span class="fu">favstats</span>(clean<span class="sc">$</span>G3 <span class="sc">~</span> clean<span class="sc">$</span>failures)<span class="sc">$</span>sd</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(sds_failure) <span class="sc">/</span> <span class="fu">min</span>(sds_failure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.902275</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(aov_failure<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-AA_Unit4_Review_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  48 181</code></pre>
</div>
</div>
<p><strong>Question</strong>: Do the residuals appear roughly normally distributed?<br>
<strong>Answer</strong>: Yes. It looks normally distributed according to qqPlot graph.</p>
<p><strong>Question</strong>: Can we trust the P-value.<br>
<strong>Answer</strong>: Yes since the data is normally distributed according to the equal standard deviation test result (1.902275 &lt; 2, test passed) and qqPlot graph.</p>
<p>State your conclusion: I have sufficient evidence to suggest that the student final grades among different past class failures, on average, are not equal to each other.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>